export const icons = new Set([
	'icon-academic-cap',
	'icon-adjustments',
	'icon-algolia',
	'icon-amazon',
	'icon-android',
	'icon-angular',
	'icon-annotation',
	'icon-anonymous',
	'icon-apple',
	'icon-appwrite',
	'icon-archive',
	'icon-arrow-circle-down',
	'icon-arrow-circle-left',
	'icon-arrow-circle-right',
	'icon-arrow-circle-up',
	'icon-arrow-down',
	'icon-arrow-expand',
	'icon-arrow-left',
	'icon-arrow-narrow-down',
	'icon-arrow-narrow-left',
	'icon-arrow-narrow-right',
	'icon-arrow-narrow-up',
	'icon-arrow-right',
	'icon-arrow-sm-down',
	'icon-arrow-sm-left',
	'icon-arrow-sm-right',
	'icon-arrow-sm-up',
	'icon-arrow-up',
	'icon-at-symbol',
	'icon-auth0',
	'icon-authentik',
	'icon-autodesk',
	'icon-azure',
	'icon-backspace',
	'icon-badge-check',
	'icon-ban',
	'icon-beaker',
	'icon-behance',
	'icon-bell',
	'icon-bitBucket',
	'icon-bitbucket',
	'icon-bitly',
	'icon-book-open',
	'icon-bookmark',
	'icon-bookmark-alt',
	'icon-box',
	'icon-briefcase',
	'icon-cake',
	'icon-calculator',
	'icon-calendar',
	'icon-camera',
	'icon-cash',
	'icon-chart-bar',
	'icon-chart-pie',
	'icon-chart-square-bar',
	'icon-chat',
	'icon-chat-alt',
	'icon-chat-alt-2',
	'icon-check',
	'icon-check-circle',
	'icon-cheveron-down',
	'icon-cheveron-left',
	'icon-cheveron-right',
	'icon-cheveron-up',
	'icon-chevron-double-down',
	'icon-chevron-double-left',
	'icon-chevron-double-right',
	'icon-chevron-double-up',
	'icon-chip',
	'icon-clipboard-arrow',
	'icon-clipboard-check',
	'icon-clipboard-copy',
	'icon-clipboard-list',
	'icon-clock',
	'icon-cloud',
	'icon-cloud-download',
	'icon-cloud-upload',
	'icon-code',
	'icon-cog',
	'icon-collection',
	'icon-color-swatch',
	'icon-cpp',
	'icon-credit-card',
	'icon-css3',
	'icon-cube',
	'icon-cube-transparent',
	'icon-currency-bangladesh',
	'icon-currency-dollar',
	'icon-currency-euro',
	'icon-currency-pound',
	'icon-currency-rupee',
	'icon-currency-yen',
	'icon-cursor-click',
	'icon-dailymotion',
	'icon-dart',
	'icon-database',
	'icon-deno',
	'icon-desktop-computer',
	'icon-device-ipad',
	'icon-device-mobile',
	'icon-discord',
	'icon-disqus',
	'icon-docker',
	'icon-document',
	'icon-document-add',
	'icon-document-download',
	'icon-document-duplicate',
	'icon-document-remove',
	'icon-document-report',
	'icon-document-search',
	'icon-document-text',
	'icon-dotnet',
	'icon-dots-circle-horizontal',
	'icon-dots-horizontal',
	'icon-dots-vertical',
	'icon-download',
	'icon-dribbble',
	'icon-dropbox',
	'icon-duplicate',
	'icon-emoji-happy',
	'icon-emoji-sad',
	'icon-etsy',
	'icon-exclamation',
	'icon-exclamation-circle',
	'icon-external-link',
	'icon-eye',
	'icon-eye-off',
	'icon-facebook',
	'icon-fast-forward',
	'icon-figma',
	'icon-film',
	'icon-filter',
	'icon-filter-line',
	'icon-finger-print',
	'icon-firefox',
	'icon-flag',
	'icon-flutter',
	'icon-folder',
	'icon-folder-add',
	'icon-folder-download',
	'icon-folder-open',
	'icon-folder-remove',
	'icon-gift',
	'icon-git',
	'icon-git-branch',
	'icon-git-commit',
	'icon-github',
	'icon-gitlab',
	'icon-globe',
	'icon-globe-alt',
	'icon-google',
	'icon-hand',
	'icon-hashtag',
	'icon-heart',
	'icon-home',
	'icon-html5',
	'icon-identification',
	'icon-inbox',
	'icon-inbox-in',
	'icon-info',
	'icon-instagram',
	'icon-ios',
	'icon-java',
	'icon-js',
	'icon-key',
	'icon-kotlin',
	'icon-light-bulb',
	'icon-lightning-bolt',
	'icon-linkedin',
	'icon-linux',
	'icon-list',
	'icon-location-marker',
	'icon-lock-closed',
	'icon-lock-open',
	'icon-logout-left',
	'icon-logout-right',
	'icon-mail',
	'icon-mail-open',
	'icon-map',
	'icon-md-library',
	'icon-medium',
	'icon-meilisearch',
	'icon-menu',
	'icon-menu-alt-1',
	'icon-menu-alt-2',
	'icon-menu-alt-3',
	'icon-menu-alt-4',
	'icon-microphone',
	'icon-microsoft',
	'icon-microsoft_edge',
	'icon-minus',
	'icon-minus-circle',
	'icon-minus-sm',
	'icon-moon',
	'icon-ms_yammer',
	'icon-msg91',
	'icon-music-note',
	'icon-newspaper',
	'icon-node',
	'icon-node_js',
	'icon-notion',
	'icon-null',
	'icon-office-building',
	'icon-okta',
	'icon-open-ai',
	'icon-opera',
	'icon-paper-airplane',
	'icon-paper-clip',
	'icon-pause',
	'icon-paypal',
	'icon-pencil',
	'icon-pencil-alt',
	'icon-perspective-api',
	'icon-phone',
	'icon-phone-incoming',
	'icon-phone-missed-call',
	'icon-phone-outgoing',
	'icon-photograph',
	'icon-php',
	'icon-pinterest',
	'icon-play',
	'icon-plus',
	'icon-plus-circle',
	'icon-plus-sm',
	'icon-podio',
	'icon-presentation-chart-1',
	'icon-presentation-chart-2',
	'icon-printer',
	'icon-product_hunt',
	'icon-puzzle',
	'icon-python',
	'icon-qrcode',
	'icon-question-mark-circle',
	'icon-react',
	'icon-receipt-refund',
	'icon-receipt-tax',
	'icon-reddit',
	'icon-refresh',
	'icon-relation',
	'icon-relationship',
	'icon-replay',
	'icon-rewind',
	'icon-rss',
	'icon-ruby',
	'icon-safari',
	'icon-salesforce',
	'icon-save',
	'icon-save-as',
	'icon-scale',
	'icon-scissors',
	'icon-search-circle',
	'icon-selector',
	'icon-server',
	'icon-share',
	'icon-shield-check',
	'icon-shield-exclamation',
	'icon-shopping-bag',
	'icon-shopping-cart',
	'icon-skype',
	'icon-slack',
	'icon-sort-ascending',
	'icon-sort-descending',
	'icon-sparkles',
	'icon-speakerphone',
	'icon-spotify',
	'icon-star',
	'icon-status-offline',
	'icon-status-online',
	'icon-stop',
	'icon-stripe',
	'icon-sun',
	'icon-support',
	'icon-swift',
	'icon-switch-horizontal',
	'icon-switch-vertical',
	'icon-table',
	'icon-telegram',
	'icon-telesign',
	'icon-template',
	'icon-terminal',
	'icon-text',
	'icon-textmagic',
	'icon-thumb-dowm',
	'icon-thumb-up',
	'icon-ticket',
	'icon-tiktok',
	'icon-toggle',
	'icon-tradeshift',
	'icon-translate',
	'icon-trash',
	'icon-trending-down',
	'icon-trending-up',
	'icon-truck',
	'icon-tumbir',
	'icon-twilio',
	'icon-twitch',
	'icon-twitter',
	'icon-unity',
	'icon-upload',
	'icon-user',
	'icon-user-add',
	'icon-user-circle',
	'icon-user-group',
	'icon-user-remove',
	'icon-users',
	'icon-variable',
	'icon-video-camera',
	'icon-view-boards',
	'icon-view-grid',
	'icon-view-grid-add',
	'icon-view-list',
	'icon-vimeo',
	'icon-vk',
	'icon-volume-off',
	'icon-volume-up',
	'icon-vonage',
	'icon-vs_code',
	'icon-vue',
	'icon-whatsapp',
	'icon-wifi',
	'icon-wordpress',
	'icon-x-circle',
	'icon-yahoo',
	'icon-yammer',
	'icon-yandex',
	'icon-ycombinator',
	'icon-youtube',
	'icon-zoom',
	'icon-zoom-in',
	'icon-zoom-out'
]);

export function getIcon(lang: string) {
	switch (lang) {
		case 'html':
			return 'icon-html5';
		case 'css':
			return 'icon-css3';
		case 'js':
			return 'icon-js';
		case 'ts':
			return 'icon-js';
		case 'txt':
			return 'icon-document-text';
		case 'jsx':
			return 'icon-js';
		case 'tsx':
			return 'icon-js';
		case 'markdown':
			return 'icon-document-text';
		case 'c':
			return 'icon-cpp';
		case 'cpp':
			return 'icon-cpp';
		case 'csharp':
			return 'icon-dotnet';
		case 'go':
			return 'icon-code';
		case 'java':
			return 'icon-java';
		case 'kotlin':
			return 'icon-kotlin';
		case 'php':
			return 'icon-php';
		case 'python':
			return 'icon-python';
		case 'ruby':
			return 'icon-ruby';
		case 'rust':
			return 'icon-code';
		case 'scala':
			return 'icon-code';
		case 'swift':
			return 'icon-swift';
		case 'dart':
			return 'icon-dart';
		default:
			return 'icon-code';
	}
}
